fix: rand race condition
go-micro/go-micro pull request #1428
Opened 2020-03-27 03:16 UTC by Astone-Chou

rand is not safe for concurrent use by multiple goroutines.

2020-03-30 20:51 UTC, vtolstov requested changes
mutex is not needed, simply seed random on func init() once and use rand functions without mutex

2020-03-30 20:52 UTC, vtolstov commented
you can use rand.Seed(time.Unix().Nano()) once on init and user rand.XXX functions with thread safe

2020-03-31 03:03 UTC, Astone-Chou commented
rand is not safe for concurrent use by multiple goroutines. u can found in the following example.

https://github.com/golang/go/blob/master/src/math/rand/rand.go#L293
```go
var globalRand = New(&lockedSource{src: NewSource(1).(*rngSource)})
...
type lockedSource struct {
	lk  sync.Mutex
	src *rngSource
}

func (r *lockedSource) Int63() (n int64) {
	r.lk.Lock()
	n = r.src.Int63()
	r.lk.Unlock()
	return
}

func (r *lockedSource) Uint64() (n uint64) {
	r.lk.Lock()
	n = r.src.Uint64()
	r.lk.Unlock()
	return
}
```

https://github.com/grpc/grpc-go/blob/master/internal/grpcrand/grpcrand.go#L30
```go
var (
	r  = rand.New(rand.NewSource(time.Now().UnixNano()))
	mu sync.Mutex
)

// Int63n implements rand.Int63n on the grpcrand global source.
func Int63n(n int64) int64 {
	mu.Lock()
	res := r.Int63n(n)
	mu.Unlock()
	return res
}

// Intn implements rand.Intn on the grpcrand global source.
func Intn(n int) int {
	mu.Lock()
	res := r.Intn(n)
	mu.Unlock()
	return res
}

// Float64 implements rand.Float64 on the grpcrand global source.
func Float64() float64 {
	mu.Lock()
	res := r.Float64()
	mu.Unlock()
	return res
}
```

2020-03-31 19:26 UTC, vtolstov commented
@Astone-Chou i know, what i want to tell you - not need to create own mutex stuff if we simply can use golang rand and have the same behaviour

2020-03-31 20:10 UTC, asim commented
I'm closing

2020-03-31 20:10 UTC, closed without merging